name: flash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.0.0
  dio: ^5.7.0
  meta: ^1.15.0
  flutter_offline: ^4.0.0
  connectivity_plus: ^6.1.2
  path_provider: ^2.0.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  vibration: ^3.1.2
  device_info_plus: ^11.2.2
  shared_preferences: ^2.5.2
  flutter_localization: ^0.3.1
  device_preview: ^1.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: PassionOne
      fonts:
        - asset: assets/fonts/PassionOne-Bold.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf

flutter_intl:
  enabled: true
